name: monero
description: Monero Dart SDK.
version: 0.0.2
repository: https://github.com/ManyMath/monerodart

environment:
  sdk: ^3.6.0-0

dependencies:
  ffi: ^2.1.3
  ffigen: ^14.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
